version: '2'
services:
    deviceapi:
        container_name: "device-api"
        build: ./api
        ports:
        - "8080:8080"
        links:
        - mongodb
        - mongodb:127.0.0.1
        environment:
        - NODE_ENV=production
        - MONGODB_ADDRESS=mongodb
        - DEBUG=server
    mongodb:
        image: mongo:latest
        volumes:
        - device-data:/data/db
volumes:
    device-data:
        driver: local