---
inventory:
    build: .
    command: npm start
    ports:
    - "8080:8080"
    links:
    - mongodb
    - mongodb:127.0.0.1
    environment:
    - NODE_ENV=production
    - MONGODB_ADDRESS=mongodb
mongodb:
    image: mongo